[project]
name = "footbath"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dax Pryce", email = "github@dax.pryce.io" }
]
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "polars>=1.44.2",
    "pydantic>=2.13.4",
    "pyhumps>=3.8.0",
    "sqlalchemy>=2.0.53",
    "typer>=0.27.2",
    "zeep[async]>=4.3.3",
]

[project.scripts]
leg-wash = "footbath:main"

[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "notebook>=7.6.1",
    "poe>=0.1.0",
    "ruff>=0.16.0",
    "ty>=0.0.63",
]
